In [2]:
import numpy as np
import pandas as pd

1. arrange(start index, end index, step size)

In [3]:
A=np.arange(2*3*4)
print('before A.shape= ', A.shape)
A=A.reshape((2,3,4)) # 3차원: cube, 2개의 3 x 4 행렬이 존재.
print('after reshape A.shape= ', A.shape)

before A.shape=  (24,)
after reshape A.shape=  (2, 3, 4)


In [4]:
# A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [5]:
A = np.arange(2*3*4).reshape((2,3,4)) # 3x 4 matrix 2개
B1 = np.arange(2*3*4).reshape((2,3,4)) # 3x 4 matrix 2개
B2 = np.arange(2*3*4).reshape((2,4,3)) # 4x3 matrix 2개
B3 = np.arange(2*3*4).reshape((3,2,4)) # 2x 4 matrix 3개
B4 = np.arange(2*3*4).reshape((3,4,2)) # 4x2 matrix 3개
B5 = np.arange(2*3*4).reshape((4,2,3)) # 2x3 matrix 4개
B6 = np.arange(2*3*4).reshape((4,3,2)) # 3x2 matrix 4개 

In [6]:
print(A)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [6]:
A[0] # 첫번째 행렬 프린트 , same as A[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
A[0][0] # 첫째 행렬의 첫째 row

array([0, 1, 2, 3])

In [18]:
A[:1] # = A[0]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [15]:
A[0,:,:1] # :1은 처음인덱스부터 1-1=0인덱스까지 출력.
# 첫째 행렬0, row는 조건없으므로 전체:, 모든 row에 대해 숫자는 첫번째만 

array([[0],
       [4],
       [8]])

In [7]:
A[0][0] # 첫번째 행렬의 첫번째 행 프린트

array([0, 1, 2, 3])

In [10]:
A[0,:,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

3. 4차원 배열



In [11]:
# np.dot(A,B1) # Eror: 마지막원소와 뒤에서 2번째 원소가 다르다.
np.dot(A,B2) # (2, 3, 2, 3)

np.dot(A,B4) # (2,3,3,2)

array([[[[  28,   34],
         [  76,   82],
         [ 124,  130]],

        [[  76,   98],
         [ 252,  274],
         [ 428,  450]],

        [[ 124,  162],
         [ 428,  466],
         [ 732,  770]]],


       [[[ 172,  226],
         [ 604,  658],
         [1036, 1090]],

        [[ 220,  290],
         [ 780,  850],
         [1340, 1410]],

        [[ 268,  354],
         [ 956, 1042],
         [1644, 1730]]]])

In [13]:
np.matmul(A,B2) # (2,3,3)

array([[[  42,   48,   54],
        [ 114,  136,  158],
        [ 186,  224,  262]],

       [[ 906,  960, 1014],
        [1170, 1240, 1310],
        [1434, 1520, 1606]]])

5. matmul과 dot의 연산 차이

In [25]:
a=np.array([[1,2],[1,2]])
b=np.array([[1,2],[1,2]])

display(a@b, np.dot(a,b)) # 2차원의 연산은 둘다 동일한 결과. 

array([[3, 6],
       [3, 6]])

array([[3, 6],
       [3, 6]])

In [14]:
a = np.random.rand(8,13,13)
b = np.random.rand(8,13,13)
c = a @ b  # Python 3.5+
d = np.dot(a, b)


In [16]:
print(a.shape,b.shape,c.shape,d.shape)

# matmul은 c를 나타내고 dot은 d연산결과를 나타내는데 dot의 경우 3차원이 4차원으로 반환됨

(8, 13, 13) (8, 13, 13) (8, 13, 13) (8, 13, 8, 13)


- matmul은 말그대로 행렬 간 곱연산이다. 따라서 각각 행렬에 대한 연산이 이루어짐
- dot은 내적으로 dot(A,B) 라면 A의 마지막축과 B의 뒤에서 2번째 축의 내적합으로 연산이 이루어짐

In [30]:
fourbyfour = np.array([
                       [1,2,3,4],
                       [3,2,1,4],
                       [5,4,6,7],
                       [11,12,13,14]
                      ])


threebyfourbytwo = np.array([
                             [[2,3],[11,9],[32,21],[28,17]],
                             [[2,3],[1,9],[3,21],[28,7]],
                             [[2,3],[1,9],[3,21],[28,7]],
                            ])

print('4x4*3x4x2 dot:\n {}\n'.format(np.dot(fourbyfour,threebyfourbytwo)))
print(np.matmul(fourbyfour,threebyfourbytwo[0]))

print('4x4*3x4x2 matmul:\n {}\n'.format(np.matmul(fourbyfour,threebyfourbytwo)))

4x4*3x4x2 dot:
 [[[232 152]
  [125 112]
  [125 112]]

 [[172 116]
  [123  76]
  [123  76]]

 [[442 296]
  [228 226]
  [228 226]]

 [[962 652]
  [465 512]
  [465 512]]]

[[232 152]
 [172 116]
 [442 296]
 [962 652]]
4x4*3x4x2 matmul:
 [[[232 152]
  [172 116]
  [442 296]
  [962 652]]

 [[125 112]
  [123  76]
  [228 226]
  [465 512]]

 [[125 112]
  [123  76]
  [228 226]
  [465 512]]]



# matmul in 3차원 이상

- 대응하는 행 열을 제외한 나머지 배열에서의 원래 인덱스 위치 유지: 
  (2,3,2)*(2,2,4)=(2,3,4) -> axis=0은 무조건 같아야함.